---
title: "#EAT-Lancet vs. #yes2meat: Understanding the digital backlash to the 'planetary health diet' - Follower network"
output: md_document
always_allow_html: yes
---


```{r setup, echo=TRUE, eval=TRUE, message=F, results='hide', cache=F}
Sys.setlocale("LC_ALL", 'en_US.UTF-8')
library(dplyr)
library(knitr)
library(kableExtra)
library(ggplot2)
library(wordcloud)
library(tm)

knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)
```

```{r loadData, echo=TRUE, eval=TRUE, message=F, results='hide', cache=T}
load("data/biofreqs.rda")
load("data/timelinefreqs.rda")
```

```{r WC1, echo=TRUE, eval=TRUE, message=F, cache=T, fig.width=6, fig.height=6}
wordcloud(words=biofreqs$words[biofreqs$community=="blue"], freq = biofreqs$freq[biofreqs$community=="blue"], min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors="blue")
```


```{r WC2, echo=TRUE, eval=TRUE, message=F, cache=T, fig.width=6, fig.height=6}
wordcloud(words=biofreqs$words[biofreqs$community=="red"], freq = biofreqs$freq[biofreqs$community=="red"], min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors="red")
```

```{r WC3, echo=TRUE, eval=TRUE, message=F, cache=T, fig.width=6, fig.height=6}
wordcloud(words=biofreqs$words[biofreqs$community=="yellow"], freq = biofreqs$freq[biofreqs$community=="yellow"], min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors="darkorange")
```

```{r WC4, echo=TRUE, eval=TRUE, message=F, cache=T, fig.width=6, fig.height=6}
wordcloud(words=biofreqs$words[biofreqs$community=="green"], freq = biofreqs$freq[biofreqs$community=="green"], min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors="darkgreen")
```


```{r Top12, echo=TRUE, eval=TRUE, message=F, cache=T, results='asis'}
d <- timelinefreqs[timelinefreqs$community=="blue",]
vs <- paste(d$word[1:12], " (", d$freq[1:12], ")", sep="")
tabledf <- data.frame(rank=seq(1,12), blue=vs)

d <- timelinefreqs[timelinefreqs$community=="yellow",]
tabledf$yellow <- paste(d$word[1:12], " (", d$freq[1:12], ")", sep="")

d <- timelinefreqs[timelinefreqs$community=="red",]
tabledf$red <- paste(d$word[1:12], " (", d$freq[1:12], ")", sep="")

d <- timelinefreqs[timelinefreqs$community=="green",]
tabledf$green <- paste(d$word[1:12], " (", d$freq[1:12], ")", sep="")


kable(tabledf, caption="Most frequent words in timelines by community.", col.names = c("Rank", "Blue community", "Yellow community", "Red community", "Green community")) %>%
  kable_styling(full_width = F)
```


```{r Followings, echo=TRUE, eval=TRUE, message=F, cache=T, results='asis'}
load("data/FollowerComm.rda")
names(FollowerComm) <- c("CommFrom", "CommTo")
tabledf <- NULL

for (comm in c("blue", "yellow", "red", "green"))
{
  N <- sum(FollowerComm$CommFrom==comm)
  toblue <- sum(FollowerComm$CommFrom==comm & FollowerComm$CommTo=="blue")
  toyellow <- sum(FollowerComm$CommFrom==comm & FollowerComm$CommTo=="yellow")
  tored <- sum(FollowerComm$CommFrom==comm & FollowerComm$CommTo=="red")
  togreen <- sum(FollowerComm$CommFrom==comm & FollowerComm$CommTo=="green")
  tabledf <- rbind(tabledf, data.frame(community=comm, 
                      toblue/N, toyellow/N, tored/N, togreen/N))
}

kable(tabledf, caption="Fractions of follower links between communities", col.names = c("From community", "to blue", "to yellow", "to red", "to green")) %>%
  kable_styling(full_width = F)

```

```{r RetweetsBefore, echo=TRUE, eval=TRUE, message=F, cache=T, results='asis'}
load("data/RT.rda")
RT %>% filter(ts <1546300800) -> RT
names(RT) <- c("ts", "CommFrom", "CommTo")
tabledf <- NULL

for (comm in c("blue", "yellow", "red", "green"))
{
  N <- sum(RT$CommFrom==comm)
  toblue <- sum(RT$CommFrom==comm & RT$CommTo=="blue")
  toyellow <- sum(RT$CommFrom==comm & RT$CommTo=="yellow")
  tored <- sum(RT$CommFrom==comm & RT$CommTo=="red")
  togreen <- sum(RT$CommFrom==comm & RT$CommTo=="green")
  tabledf <- rbind(tabledf, data.frame(community=comm, 
                      toblue/N, toyellow/N, tored/N, togreen/N))
}

kable(tabledf, caption="Fractions of retweets between communities by the end of 2018", col.names = c("From community", "to blue", "to yellow", "to red", "to green")) %>%
  kable_styling(full_width = F)
```


```{r RetweetsAfter, echo=TRUE, eval=TRUE, message=F, cache=T, results='asis'}
load("data/RT.rda")
RT %>% filter(ts>=1547683200 & ts <1548547200) -> RT
names(RT) <- c("ts", "CommFrom", "CommTo")
tabledf <- NULL

for (comm in c("blue", "yellow", "red", "green"))
{
  N <- sum(RT$CommFrom==comm)
  toblue <- sum(RT$CommFrom==comm & RT$CommTo=="blue")
  toyellow <- sum(RT$CommFrom==comm & RT$CommTo=="yellow")
  tored <- sum(RT$CommFrom==comm & RT$CommTo=="red")
  togreen <- sum(RT$CommFrom==comm & RT$CommTo=="green")
  tabledf <- rbind(tabledf, data.frame(community=comm, 
                      toblue/N, toyellow/N, tored/N, togreen/N))
}

kable(tabledf, caption="Fractions of retweets between communities during the ten days after the report release", col.names = c("From community", "to blue", "to yellow", "to red", "to green")) %>%
  kable_styling(full_width = F)
```

```{r TotalRetweets, echo=TRUE, eval=TRUE, message=F, cache=T, results='asis'}
load("data/communitydf.rda")
load("data/eatlancet_tweets.rda")

rtdf <- inner_join(eatlancet_tweets, communitydf, by=c("USER_id_str" = "v_name"))

tabledf <- NULL

for (comm in c("blue", "yellow", "red", "green"))
{
  Nusers <- sum(communitydf$community==comm)
  nRT <- sum(rtdf$retweet_count[rtdf$community==comm])
  mnRT <- nRT/Nusers
  tabledf <- rbind(tabledf, data.frame(community=comm, users=Nusers, retweets=nRT, retweetsperuser=mnRT))
}

kable(tabledf, caption="Retweet statistics per community", col.names = c("Community", "Number of users", "Total retweets", "Retweets per user")) %>%
  kable_styling(full_width = F)

```


Bot scores:
```{r, echo=TRUE, eval=TRUE, fig.width=5, fig.height=5}
load("data/communitydf.rda")
load("data/eatlancet_botscores.rda")
inner_join(eatlancet_botscores, communitydf, by=c("USER_id_str"="v_name")) %>%
  select(USER_id_str, universalScore, englishScore, community) -> botcommdf

cdfGreen <- ecdf(botcommdf$universalScore[botcommdf$community=="green"])
cdfRed <- ecdf(botcommdf$universalScore[botcommdf$community=="red"])
cdfBlue <- ecdf(botcommdf$universalScore[botcommdf$community=="blue"])
cdfYellow <- ecdf(botcommdf$universalScore[botcommdf$community=="yellow"])
cdfAll <- ecdf(botcommdf$universalScore)

x <- seq(0,1, by=0.01)
plot(x, cdfGreen(x), col="darkgreen", type="l", lwd=2, xlab = "Universal Bot Score", ylab = "CDF")
lines(x, cdfRed(x), col="red", lwd=2)
lines(x, cdfBlue(x), col="blue", lwd=2)
lines(x, cdfYellow(x), col="darkorange", lwd=2)
lines(x, cdfAll(x), col=rgb(0,0,0,0.6),lwd=3)


cdfGreen <- ecdf(botcommdf$englishScore[botcommdf$community=="green"])
cdfRed <- ecdf(botcommdf$englishScore[botcommdf$community=="red"])
cdfBlue <- ecdf(botcommdf$englishScore[botcommdf$community=="blue"])
cdfYellow <- ecdf(botcommdf$englishScore[botcommdf$community=="yellow"])
cdfAll <- ecdf(botcommdf$englishScore)

x <- seq(0,1, by=0.01)
plot(x, cdfGreen(x), col="darkgreen", type="l", lwd=2, xlab = "English Bot Score", ylab = "CDF")
lines(x, cdfRed(x), col="red", lwd=2)
lines(x, cdfBlue(x), col="blue", lwd=2)
lines(x, cdfYellow(x), col="darkorange", lwd=2)
lines(x, cdfAll(x), col=rgb(0,0,0,0.6),lwd=3)

```


```{r, echo=TRUE, eval=TRUE, fig.width=5, fig.height=5}
load("data/eatlancet_URLshares.rda")
eatlancet_URLshares$USER_id_str <- as.character(eatlancet_URLshares$USER_id_str)
eatlancet_URLshares %>% distinct(id_str, .keep_all = T) -> eatlancet_URLshares

eatlancet_URLshares <- inner_join(eatlancet_URLshares, eatlancet_botscores, by="USER_id_str")

cdfRed <- ecdf(eatlancet_URLshares$universalScore[eatlancet_URLshares$class=="Anti"])
cdfBlue <- ecdf(eatlancet_URLshares$universalScore[eatlancet_URLshares$class=="Pro"])
cdfGray <- ecdf(eatlancet_URLshares$universalScore[eatlancet_URLshares$class=="Neutral"])

x <- seq(0,1, by=0.01)
plot(x, cdfBlue(x), col="blue", type="l", lwd=2, xlab = "Universal Bot Score", ylab = "CDF")
lines(x, cdfRed(x), col="red", lwd=2)
lines(x, cdfGray(x), col=rgb(0,0,0,0.6),lwd=2)

cdfRed <- ecdf(eatlancet_URLshares$englishScore[eatlancet_URLshares$class=="Anti"])
cdfBlue <- ecdf(eatlancet_URLshares$englishScore[eatlancet_URLshares$class=="Pro"])
cdfGray <- ecdf(eatlancet_URLshares$englishScore[eatlancet_URLshares$class=="Neutral"])
legend("bottomright", c("Shares anti EAT-Lancet", "Shares pro EAT-Lancet", 
                        "Shares neutral EAT-Lancet"), col=c("red", "blue", rgb(0,0,0,0.6)), lwd=2)

x <- seq(0,1, by=0.01)
plot(x, cdfBlue(x), col="blue", type="l", lwd=2, xlab = "English Bot Score", ylab = "CDF")
lines(x, cdfRed(x), col="red", lwd=2)
lines(x, cdfGray(x), col=rgb(0,0,0,0.6),lwd=2)
legend("bottomright", c("Shares anti EAT-Lancet", "Shares pro EAT-Lancet", 
                        "Shares neutral EAT-Lancet"), col=c("red", "blue", rgb(0,0,0,0.6)), lwd=2)

```


Potential message reach by community based on follower numbers

```{r, echo=TRUE, eval=TRUE}
load("data/community_followers.rda")

community_follower_stats_filtered <- community_followers %>%
  filter(n_tweets > 2) %>%
  group_by(community) %>%
  summarise(n_users = n(),
            sum_tweets = sum(n_tweets),
            sum_followers = sum(n_followers),
            median_followers = median(n_followers),
            mean_followers = mean(n_followers),
            cumulative_tweet_reach = sum(n_followers * n_tweets))

community_follower_stats_filtered %>%
  select(community, n_users, sum_tweets, median_followers, sum_followers, cumulative_tweet_reach) %>%
  arrange(-n_users) %>%
  kable(format = "html", 
        digits = c(0, 0, 0, 0, 1, 0), 
        col.names = c("Community", "Users (N)", "Tweets (N)", "Followers (median)", "Followers (sum)", "Cumulative reach"))
```

