---
title: "#EAT-Lancet vs. #yes2meat: Understanding the digital backlash to the 'planetary health diet' - Sentiment analysis"
output: md_document
always_allow_html: yes
---

```{r setup, echo=FALSE, eval=TRUE, message=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)

library(dplyr)
library(knitr)
library(kableExtra)
```

Percentage of tweets with each sentiment label for eatlancet and yes2meat:

```{r percentages, echo=TRUE, eval=TRUE, results="asis"}
load("data/eatlancet_tweets.rda")
df <- read.csv("data/sampleTweets_Annotated.csv", colClasses=rep("character", 7))
names(df) <- c("id", "URL", "Positive", "Negative", "Neutral", "Irrelevant", "NE")
df <- inner_join(df, eatlancet_tweets, by=c("id"="id_str"))

df %>% filter(NE != "X") -> df

tabledf <- data.frame(
  Term=c("EAT-Lancet", "yes2meat"),
  Positive=c(round(sum(df$Positive[df$EATLancet]=="X")/sum(df$EATLancet)*100,2),round(sum(df$Positive[df$yes2meat]=="X")/sum(df$yes2meat)*100,2)),
  Negative=c(round(sum(df$Negative[df$EATLancet]=="X")/sum(df$EATLancet)*100,2),round(sum(df$Negative[df$yes2meat]=="X")/sum(df$yes2meat)*100,2)),
  Neutral=c(round(sum(df$Neutral[df$EATLancet]=="X")/sum(df$EATLancet)*100,2),round(sum(df$Neutral[df$yes2meat]=="X")/sum(df$yes2meat)*100,2)),
  Irrelevant=c(round(sum(df$Irrelevant[df$EATLancet]=="X")/sum(df$EATLancet)*100,2),round(sum(df$Irrelevant[df$yes2meat]=="X")/sum(df$yes2meat)*100,2)))

kable(tabledf, caption="Sentiment by term") %>%
  kable_styling(full_width = F)
```

```{r percentagesRatio, echo=TRUE, eval=TRUE}

sum(df$Negative[df$yes2meat]=="X")/(sum(df$Positive[df$yes2meat]=="X") + sum(df$Neutral[df$yes2meat]=="X"))
```




Sentiment statistics per community:
```{r, echo=TRUE, eval=TRUE}
tdf <- read.csv("data/CommunitySelectedTweets_Annotated.csv", colClasses=rep("character", 6))
names(tdf) <- c("id", "Positive", "Negative", "Neutral", "Irrelevant", "NE")

load("data/eatlancet_tweets.rda")
eatlancet_tweets %>% distinct(id_str, .keep_all = T) -> tweets  # We remove duplicates by tweet id
tweets$Date <- as.Date(substr(tweets$created_at,1,10))
#We analyze two weeks after the report was released
tweets %>% filter(Date >= "2019-01-16" & Date <= "2019-01-31") -> tweets

tdf <- left_join(tdf, tweets, by=c("id"="id_str"))

load("data/communitydf.rda")
tdf <- inner_join(tdf, communitydf, by=c("USER_id_str"="v_name"))

tabledf <- data.frame(Sentiment=c("Positive", "Negative", "Neutral", "Irrelevant"))
for (color in c("blue", "red", "yellow", "green"))
{
  Pos <- sum(tdf$Positive[tdf$community==color]=="X")/sum(tdf$community==color)*100
  Neg <- sum(tdf$Negative[tdf$community==color]=="X")/sum(tdf$community==color)*100
  Neu <- sum(tdf$Neutral[tdf$community==color]=="X")/sum(tdf$community==color)*100
  Irr <- sum(tdf$Irrelevant[tdf$community==color]=="X")/sum(tdf$community==color)*100
  tabledf[[color]] <- c(Pos, Neg, Neu, Irr)
}


kable(tabledf, caption="Sentiment by community") %>%
  kable_styling(full_width = F)

```
